### PR TITLE
Udhay/go sdk update

### PR DESCRIPTION
**Pull request by udhaykumarbala**
- 0G Go SDK guide updated
- Constant function added to derive value from config
- Github repo link updated

- - -
This change is [Reviewable](https://reviewable.io/reviews/0glabs/0g-doc/27)

### CODE REVIEW

**Comment by udhaykumarbala** [comment]
Hi @roycclu, I have the code according to the comments

- changed 0g to 0G
- added variables on the parameters
- Created a new function to get values from env,  for RPC endpoints, indexer endpoints. I'll create one more PR later to move all the variables like contract address & endpoints into the env

The build succeeded on my local but it is failing on vercel, I'm unable to see the issue on vercel since i' don't have access to it. Can you please share the screenshots of the issue. I'll check & resolve the issue

**Comment by roycclu** [comment]
Hi @udhaykumarbala , believe it's because you directly added a .env and edited docasaurus config file. 

If you want to edit .env files of specific repos like go SDK, pls create PR's separately for those repos. 

Some of the docasaurus config edits are helpful like fixing the URL link, those I can edit directly and fix this PR. 

Once those are corrected, vercel should work.

Thanks so much!

**Comment by roycclu** [comment]
Oops, missed one thing, and you edit the [src/components/GetConstantValue.tsx], which is not needed. Thanks so much!

**Comment by udhaykumarbala** [comment]
Thanks @roycclu,  I pushed the changes.

I added the GetConstantValue as a common function so that we can get the value from env with this function that can be used to show contract addresses, endpoints & other variables. It will be easier to change & can have different deployments for devnet, testnet & mainnet.


I love the feedbacks that you have given, i'd love to contribute on the SDK's also if possible 😇

**Comment by roycclu** [comment]
Hi @udhaykumarbala , 

Appreciate your contribution and updating the changes. 
Of course, would love to have you contribute to cleaner setup of environmental variables. We should have some clarity on how we'd go about testnet/mainnet soon and will keep you posted. 

In the meantime, if you contribute to SDK directly, other team members manage those repos, but feel free to ping me or Gathin. 

Cheers.

**Review by roycclu — DISMISSED** [review]

**Review by roycclu — APPROVED** [review]

**Pull request merged**
